
all: Server Lysander

Server: a2-server2.c
	gcc a2-server2.c -o Server -Wall
	
Lysander: lysander.c
	gcc lysander.c -o Lysander -Wall
    
clean:
	rm -rf Server
	rm -rf Lysander
	rm -rf blarg2.txt
	rm -rf Assignment2b.pdf
	rm -rf *~

