all : samplerequest Shrike

samplerequest : 3210-samplerequest.c
	gcc 3210-samplerequest.c -Wall -o samplerequest

Shrike: Shrike.c
	gcc Shrike.c -Wall -o Shrike

clean :
	rm samplerequest
	rm Shrike
